define([], function() {
  return {
    "SearchInputPlaceholder": "Indsæt søgeinformation...",
    "SearchBoxQuerySuggestionsSettings": "Instillinger for søgeforslag",
    "SearchBoxEnableQuerySuggestions": "Aktiver mulighed for forespørgsler",
    "SearchBoxNewPage": "Muligheder for søgefelt",
    "SearchBoxSearchInNewPageLabel": "Send forespørgslen til en ny side",
    "SearchBoxPageUrlLabel": "Side-URL",
    "SearchBoxUrlErrorMessage": "Venligst angiv en gyldig URL.",
    "SearchBoxQuerySettings": "Default-instillinger for søgeforespørgsler",
    "SearchBoxSameTabOpenBehavior": "Anvend den nuværende fane",
    "SearchBoxNewTabOpenBehavior": "Åben i en ny fane",
    "SearchBoxPageOpenBehaviorLabel": "Åbningsadfærd",
    "SearchBoxQueryPathBehaviorLabel": "Metode",
    "SearchBoxUrlFragmentQueryPathBehavior": "URL-fragment",
    "SearchBoxQueryStringQueryPathBehavior": "Forespørgselsparameter",
    "SearchBoxQueryStringParameterName": "Parameternavn",
    "SearchBoxQueryParameterNotEmpty": "Angiv venligst en værdi for parameteret",
    "SearchBoxQueryNlpSettings": "Søgeforspørgsel forbedret",
    "SearchBoxQueryNlpSettingsDescription": "Anvend denne tjeneste til at forbedre søgeforespørgslen ved at spore brugerhensigter og få mere relevante søgenøgleord med Microsoft LUIS.",
    "SearchBoxUserQueryNlpLabel": "Anvend Natural Language Processing-tjeneste",
    "SearchBoxServiceUrlLabel": "Tjeneste-URL",
    "SearchBoxServiceUrlDescription": "Bemærk: Sørg for at serveren tillader cross-origin kald fra andre domæner ('{0}') i CORS-instillingerne.",
    "SearchBoxServiceUrlErrorMessage": "Anvend venligst en gyldig URL",
    "SearchBoxUseDebugModeLabel": "Aktiver fejlretningstilstand",
    "SearchBoxUseStagingEndpoint": "Anvend LUIS opsætningspunkt",
    "UrlNotResolvedErrorMessage": "URL '{0}' kan ikke blive fundet. Error: '{1}'.",
    "SearchBoxPlaceholderTextLabel": "Variabel tekst i søgeknap",
    "CancelButtonText": "Afbryd",
    "DialogButtonLabel": "Rediger template",
    "DialogButtonText": "Rediger template",
    "SaveButtonText": "Gem",
    "DynamicData": {
      "UseDynamicDataSourceLabel": "Brug en dynamisk datakilde",
      "SearchQueryPropertyLabel": "Søg forespørgsel",
      "RawInputValuePropertyLabel": "Rå brugersøgeforespørgsel",
      "EnhancedQueryPropertyLabel": "NLP forbedret søgeforespørgsel"
    },
    "DebugPanel": {
      "HeaderLabel": "NLP fejlretningsinformation",
      "DetectedLanguageLabel": "Sprog påvist",
      "RecognizedEntitiesLabel": "Anerkendte enheder",
      "TopScoringIntentNameLabel": "Topscorende enheder",
      "TopScoringIntentScoreLabel": "Topscorende enhedsfortrolighed",
      "EnhancedQueryLabel": "Forbedret søgeforespørgsel",
      "AlteredQueryLabel": "Rettet forespørgsel"
    },
    "SuggestionProviders": {
      "EditSuggestionProvidersLabel": "Konfigurér forslag",
      "SuggestionProvidersLabel": "Forslagsleverandører",
      "SuggestionProvidersDescription": "Aktivér eller deaktivér individuelle forslagsleverandører",
      "EnabledPropertyLabel": "Aktiv",
      "ProviderNamePropertyLabel": "Navn",
      "ProviderDescriptionPropertyLabel": "Beskrivelse",
      "InlineTemplateContentLabel": "Inline skabelon",
      "ExternalUrlLabel": "Ekstern skabelon-Url",
      "InlineTemplateEditPanelTitle": "Rediger skabelon med forslag",
      "DefaultSuggestionGroupName": "Anbefalet",
      "SharePointSuggestionGroupName": "Andre har søgt efter",
    }
  }
});
