define([], function() {
  return {
    "SearchInputPlaceholder": "Voer uw zoekopdracht in...",
    "SearchBoxQuerySuggestionsSettings": "Zoeksuggestie instellingen",
    "SearchBoxEnableQuerySuggestions": "Sta zoeksuggesties toe",
    "SearchBoxNewPage": "Zoekvak instellingen",
    "SearchBoxSearchInNewPageLabel": "Stuur de zoekopdracht naar een nieuwe pagina",
    "SearchBoxPageUrlLabel": "Pagina URL",
    "SearchBoxUrlErrorMessage": "Voer een geldige URL in",
    "SearchBoxQuerySettings": "Standaard zoekopdracht instellingen",
    "SearchBoxSameTabOpenBehavior": "Gebruik huidige tab",
    "SearchBoxNewTabOpenBehavior": "Open in nieuwe tab",
    "SearchBoxPageOpenBehaviorLabel": "Gedrag van openen",
    "SearchBoxQueryPathBehaviorLabel": "Methode",
    "SearchBoxUrlFragmentQueryPathBehavior": "URL fragment",
    "SearchBoxQueryStringQueryPathBehavior": "Zoekopdracht parameter",
    "SearchBoxQueryStringParameterName": "Zoekopdracht parameter naam",
    "SearchBoxQueryParameterNotEmpty": "Geef een parameter op",
    "SearchBoxQueryNlpSettings": "Zoekopdracht uitbreiding",
    "SearchBoxQueryNlpSettingsDescription": "Gebruik deze dienst om de zoekopdracht te verrijken met LUIS voor meer relevante resultaten.",
    "SearchBoxUserQueryNlpLabel": "Gebruik Natural Language Processing dienst",
    "SearchBoxServiceUrlLabel": "Service URL",
    "SearchBoxServiceUrlDescription": "Opmerking: configureer voor allows cross-origin calls van dit domein ('{0}') in CORS instellingen.",
    "SearchBoxServiceUrlErrorMessage": "Voer een geldige URL in",
    "SearchBoxUseDebugModeLabel": "Schakel debug mode in",
    "SearchBoxUseStagingEndpoint": "Gebruik LUIS staging endpoint",
    "UrlNotResolvedErrorMessage": "URL '{0}' kan niet worden gebruikt. Error: '{1}'.",
    "SearchBoxPlaceholderTextLabel": "Tijdelijke aanduiding in zoekvak",
    "CancelButtonText": "Annuleren",
    "DialogButtonLabel": "Styling",
    "DialogButtonText": "Bewerk template",
    "SaveButtonText": "Opslaan",
    "DynamicData": {
      "UseDynamicDataSourceLabel": "Gebruik een dynamische data bron",
      "SearchQueryPropertyLabel": "Zoek opdracht",
      "RawInputValuePropertyLabel": "Ruwe gebruikers zoekopdrach",
      "EnhancedQueryPropertyLabel": "NLP verrijkte zoekopdracht"
    },
    "DebugPanel": {
      "HeaderLabel": "NLP debug informatie",
      "DetectedLanguageLabel": "Herkende taal",
      "RecognizedEntitiesLabel": "Herkende entiteit",
      "TopScoringIntentNameLabel": "Hoogst scorende entiteit",
      "TopScoringIntentScoreLabel": "Hoogst scorende indenteit (vertrouwen)",
      "EnhancedQueryLabel": "Verrijkte zoekopdracht",
      "AlteredQueryLabel": "Aangepaste zoekopdracht"
    },
    "SuggestionProviders": {
      "EditSuggestionProvidersLabel": "Configurar sugerencias",
      "SuggestionProvidersLabel": "Forslag Providers",
      "SuggestionProvidersDescription": "Aktivere eller deaktivere individuelle forslags leverandører.",
      "EnabledPropertyLabel": "Aktive",
      "ProviderNamePropertyLabel": "Navn",
      "ProviderDescriptionPropertyLabel": "Beskrivelse",
      "InlineTemplateContentLabel": "Innebygd mal",
      "ExternalUrlLabel": "URL for ekstern mal",
      "InlineTemplateEditPanelTitle": "Rediger forslags mal",
      "DefaultSuggestionGroupName": "Anbefalt",
      "SharePointSuggestionGroupName": "Andre har søke etter",
    }
  }
});
