define([], function() {
  return {
    "SearchInputPlaceholder": "Ange sökinformation...",
    "SearchBoxQuerySuggestionsSettings": "Inställningar för sökförslag",
    "SearchBoxEnableQuerySuggestions": "Aktivera frågeförslag",
    "SearchBoxNewPage": "Alternativ för sökrutan",
    "SearchBoxSearchInNewPageLabel": "Skicka frågan till en ny sida",
    "SearchBoxPageUrlLabel": "Sidans URL",
    "SearchBoxUrlErrorMessage": "Ange en giltig URL",
    "SearchBoxQuerySettings": "Inställningar för sökfrågor",
    "SearchBoxSameTabOpenBehavior": "Använd den nuvarande fliken",
    "SearchBoxNewTabOpenBehavior": "Öppna i ny flik",
    "SearchBoxPageOpenBehaviorLabel": "Öppningsbeteende",
    "SearchBoxQueryPathBehaviorLabel": "Metod",
    "SearchBoxUrlFragmentQueryPathBehavior": "URL-fragment",
    "SearchBoxQueryStringQueryPathBehavior": "Frågeparameter",
    "SearchBoxQueryStringParameterName": "Parameternamn",
    "SearchBoxQueryParameterNotEmpty": "Ange ett värde för parametern",
    "SearchBoxQueryNlpSettings": "Förbättring av sökfrågor",
    "SearchBoxQueryNlpSettingsDescription": "Använd den här tjänsten för att förbättra sökfrågan genom att upptäcka användarens avsikter och få mer relevanta sökord med Microsoft LUIS.",
    "SearchBoxUserQueryNlpLabel": "Använd Natural Language Processing tjänst",
    "SearchBoxServiceUrlLabel": "Tänste URL",
    "SearchBoxServiceUrlDescription": "Observera: se till att servern tillåter anrop från andra domäner från den här domänen ('{0}') i CORS-inställningarna.",
    "SearchBoxServiceUrlErrorMessage": "Ange en giltig URL",
    "SearchBoxUseDebugModeLabel": "Aktivera felsökningsläge",
    "SearchBoxUseStagingEndpoint": "Använd LUIS-anslutningspunkten",
    "UrlNotResolvedErrorMessage": "URL: '{0}' kan inte tolkas. Fel: '{1}'.",
    "SearchBoxPlaceholderTextLabel": "Text som platshållare i sökrutan",
    "CancelButtonText": "Avbryt",
    "DialogButtonLabel": "Redigera mall",
    "DialogButtonText": "Redigera mall",
    "SaveButtonText": "Spara",
    "DynamicData": {
      "UseDynamicDataSourceLabel": "Använd en dynamisk datakälla",
      "SearchQueryPropertyLabel": "Sök fråga",
      "RawInputValuePropertyLabel": "Obearbetad användarfråga",
      "EnhancedQueryPropertyLabel": "NLP förbättrad sökfråga"
    },
    "DebugPanel": {
      "HeaderLabel": "NLP felsökningsinformation",
      "DetectedLanguageLabel": "Upptäckt språk",
      "RecognizedEntitiesLabel": "Igenkänd enheter",
      "TopScoringIntentNameLabel": "Toppresultat enheter",
      "TopScoringIntentScoreLabel": "Toppresultat tillförlitlighet",
      "EnhancedQueryLabel": "Förbättrad sökfråga",
      "AlteredQueryLabel": "Rättad sökfråga"
    },
    "SuggestionProviders": {
      "EditSuggestionProvidersLabel": "Konfigurera förslag",
      "SuggestionProvidersLabel": "Förslagsleverantörer",
      "SuggestionProvidersDescription": "Aktivera eller inaktivera enskilda förslagsleverantörer.",
      "EnabledPropertyLabel": "Aktiv",
      "ProviderNamePropertyLabel": "Namn",
      "ProviderDescriptionPropertyLabel": "Beskrivning",
      "InlineTemplateContentLabel": "Inline mall",
      "ExternalUrlLabel": "Extern mall URL",
      "InlineTemplateEditPanelTitle": "Redigera förslagsmall",
      "DefaultSuggestionGroupName": "Rekommenderad",
      "SharePointSuggestionGroupName": "Andra har sökt efter",
    }
  }
});
