// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'isLink': string;
  'searchVerticals': string;
}
export const cssExports: CssExports;
export default cssExports;
