define([], function () {
  return {
    "RefinersConfigurationGroupName": "Instillinger for filter",
    "ShowBlankLabel": "Vis tomt, hvis intet resultat",
    "WebPartTitle": "Webdelstitel",
    "StylingSettingsGroupName": "Styling-muligheder",
    "AppliedRefinersLabel": "Anvendte filtre",
    "PlaceHolderEditLabel": "Rediger",
    "PlaceHolderConfigureBtnLabel": "Konfigurér",
    "PlaceHolderIconText": "Filtrér webdel",
    "PlaceHolderDescription": "Denne komponent viser søgefiltre",
    "NoFilterConfiguredLabel": "Intet filter tilgængeligt",
    "RemoveAllFiltersLabel": "Fjern alle filtre",
    "ShowBlankEditInfoMessage": "Intet filter at vise. Denne webdel vil forblive tom i visningstilstand i overensstemmelse med instillingerne.",
    "RefinersConfiguration": "Konfiguration og filtre",
    "SearchResultsLabel": "Søgeresultater",
    "SearchQueryLabel": "Forespørgselssøgning",
    "FilterResultsButtonLabel": "Filtre",
    "SelectedFiltersLabel": "Valgte filtre:",
    "RefinerLayoutLabel": "Filter-layout",
    "ConnectToSearchResultsLabel": "Tilslut til søgeresultatens webdel",
    "Refiners": {
      "RefinersFieldLabel": "Begrænsninger",
      "RefinerManagedPropertyField": "Håndterede egenskabsfilter",
      "RefinerDisplayValueField": "Filternavn som skal vises",
      "RefinerTemplateField": "Filterskabelon",
      "RefinersFieldDescription": "Specificerer håndteret egenskab der anvendes som filter. Hvis der ikke er nogle værdier for en filteregenskab, vil den ikke figurere i panelet.",
      "EditRefinersLabel": "Rediger filtre",
      "AvailableRefinersLabel": "Tilgængelige filtre",
      "ApplyFiltersLabel": "Anvend",
      "ClearFiltersLabel": "Ryd",
      "ShowExpanded": "Udvid filter pr. default",
      "showValueFilter": "Vis filter for forfinelsesværdier",
      "Templates": {
        "RefinementItemTemplateLabel": "Standard filter",
        "MutliValueRefinementItemTemplateLabel": "Flerværdi-filtre",
        "PersonaRefinementItemLabel": "Person",
        "DateRangeRefinementItemLabel": "Datointernal",
        "FixedDateRangeRefinementItemLabel": "Datointerval (faste intervaller)",
        "FileTypeRefinementItemTemplateLabel": "Filtype",
        "FileTypeMutliValueRefinementItemTemplateLabel": "Flere filtyper",
        "ContainerTreeRefinementItemTemplateLabel": "Container-træer",
        "DateFromLabel": "Fra",
        "DateTolabel": "Til",
        "DatePickerStrings": {
          "months": ['Januar', 'Februar', 'Marts', 'April', 'Maj', 'Juni', 'Juli', 'August', 'September', 'Oktober', 'November', 'December'],
          "shortMonths": ['Jan', 'Feb', 'Mar', 'Apr', 'Maj', 'Jun', 'Jul', 'Aug', 'Sep', 'Okt', 'Nov', 'Dec'],
          "days": ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
          "shortDays": ['S', 'M', 'T', 'O', 'T', 'F', 'L'],
          "goToToday": 'Gå til i dag',
          "prevMonthAriaLabel": 'Gå til foregående måned',
          "nextMonthAriaLabel": 'Gå til næste måned',
          "prevYearAriaLabel": 'Gå til foregående år',
          "nextYearAriaLabel": 'Gå til næste år',
          "closeButtonAriaLabel": 'Luk datovælger',
          "isRequiredErrorMessage": 'Startdato kræves',
          "invalidInputErrorMessage": 'Ugyldigt dataformat.'
        },
        "DateIntervalStrings": {
          "AnyTime": "Når som helst",
          "PastDay": "Seneste 24 timer",
          "PastWeek": "Seneste uge",
          "PastMonth": "Seneste måned",
          "Past3Months": "Seneste 3 måneder",
          "PastYear": "Seneste år",
          "Older": "Ældre end et år"
        },
        "RefinerSortTypeLabel": "Sorteringsordning",
        "RefinerSortTypeAlphabetical": "Alfabetisk",
        "RefinerSortTypeByNumberOfResults": "Efter antal resultater",
        "RefinerSortTypeSortOrderLabel": "Sortér rækkefølge",
        "RefinerSortTypeSortDirectionAscending": "Stigende",
        "RefinerSortTypeSortDirectionDescending": "Faldende"
      }
    },
  }
});
