define([], function () {
  return {
    "RefinersConfigurationGroupName": "Inställningar för filter",
    "ShowBlankLabel": "Visa tomt om inget resultat",
    "WebPartTitle": "Webbdels titel",
    "StylingSettingsGroupName": "Utseende inställningar",
    "AppliedRefinersLabel": "Tillämpande filter",
    "PlaceHolderEditLabel": "Redigera",
    "PlaceHolderConfigureBtnLabel": "Inställningar",
    "PlaceHolderIconText": "Filter webbdel",
    "PlaceHolderDescription": "Den här komponenten visar sök filter",
    "NoFilterConfiguredLabel": "Inget filter tillgängligt",
    "RemoveAllFiltersLabel": "Ta bort alla filter",
    "ShowBlankEditInfoMessage": "Inget filter att visa. Denna webbdel kommer att förbli tom i visningsläge enligt inställningar.",
    "RefinersConfiguration": "Filter inställningar",
    "SearchResultsLabel": "Sökresultat",
    "SearchQueryLabel": "Sök fråga",
    "FilterResultsButtonLabel": "Filter",
    "SelectedFiltersLabel": "Valda filter:",
    "RefinerLayoutLabel": "Filter utseende",
    "ConnectToSearchResultsLabel": "Anslut till sökresultatens webbdel",
    "Refiners": {
      "RefinersFieldLabel": "Begränsningar",
      "RefinerManagedPropertyField": "Hanterad egenskaps filter",
      "RefinerDisplayValueField": "Filternamn som ska visas",
      "RefinerTemplateField": "Filtermall",
      "RefinersFieldDescription": "Anger hanterade egenskaper som används som filter. Om det inte finns några värden för en filteregenskap visas den inte på panelen.",
      "EditRefinersLabel": "Redigera filter",
      "AvailableRefinersLabel": "Tillgängliga filter",
      "ApplyFiltersLabel": "Tillämpa",
      "ClearFiltersLabel": "Rensa",
      "ShowExpanded": "Expandera filter som standard",
      "showValueFilter": "Visa filter för avgränsningar",
      "Templates": {
        "RefinementItemTemplateLabel": "Standard filter",
        "MutliValueRefinementItemTemplateLabel": "Fler värdes filter",
        "PersonaRefinementItemLabel": "Person",
        "DateRangeRefinementItemLabel": "Datumintervall",
        "FixedDateRangeRefinementItemLabel": "Datumintervall (fasta intervall)",
        "FileTypeRefinementItemTemplateLabel": "Filtyp",
        "FileTypeMutliValueRefinementItemTemplateLabel": "Flera filtyp",
        "ContainerTreeRefinementItemTemplateLabel": "Container-träd",
        "DateFromLabel": "Från",
        "DateTolabel": "Till",
        "DatePickerStrings": {
          "months": ['Januari', 'Februari', 'Mars', 'April', 'Maj', 'Juni', 'Juli', 'Augusti', 'September', 'Oktober', 'November', 'December'],
          "shortMonths": ['Jan', 'Feb', 'Mar', 'Apr', 'Maj', 'Jun', 'Jul', 'Aug', 'Sep', 'Okt', 'Nov', 'Dec'],
          "days": ['Söndag', 'Måndag', 'Tisdag', 'Onsdag', 'Torsdag', 'Fredag', 'Lördag'],
          "shortDays": ['S', 'M', 'T', 'O', 'T', 'F', 'L'],
          "goToToday": 'Gå till idag',
          "prevMonthAriaLabel": 'Gå till föregående månad',
          "nextMonthAriaLabel": 'Gå till nästa månad',
          "prevYearAriaLabel": 'Gå till föregående år',
          "nextYearAriaLabel": 'Gå till nästa år',
          "closeButtonAriaLabel": 'Stäng datumväljaren',
          "isRequiredErrorMessage": 'Startdatum krävs.',
          "invalidInputErrorMessage": 'Ogiltigt datumformat.'
        },
        "DateIntervalStrings": {
          "AnyTime": "När som helst",
          "PastDay": "Senaste 24 timarna",
          "PastWeek": "Senaste vecka",
          "PastMonth": "Senaste månaden",
          "Past3Months": "Senaste 3 månaderna",
          "PastYear": "Senaste år",
          "Older": "Äldre än ett år"
        },
        "RefinerSortTypeLabel": "Sorteringsordning",
        "RefinerSortTypeAlphabetical": "Alfabetisk",
        "RefinerSortTypeByNumberOfResults": "Efter antal resultat",
        "RefinerSortTypeSortOrderLabel": "Sorteringriktning",
        "RefinerSortTypeSortDirectionAscending": "Stigande",
        "RefinerSortTypeSortDirectionDescending": "Fallande"
      }
    },
  }
});
