// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'overlay': string;
  'searchWp': string;
  'searchWp__buttonBar': string;
  'searchWp__buttonBar__button': string;
  'searchWp__filterResultBtn': string;
  'searchWp__noresult': string;
  'searchWp__sortDropdown': string;
  'searchWp__sortPanel__body': string;
  'searchWp__sortResultBtn': string;
}
export const cssExports: CssExports;
export default cssExports;
