// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'ace_autocomplete': string;
  'ace_editor': string;
}
export const cssExports: CssExports;
export default cssExports;
