define([], function() {
    return {
        "SearchQuerySettingsGroupName": "Instillinger for søgeforespørgsler",
        "SearchSettingsGroupName": "Instillinger for søg",
        "SearchQueryKeywordsFieldLabel": "Søgeord for søgeforespørgsler",
        "QueryTemplateFieldLabel": "Forespørgselsskabelon",
        "SelectedPropertiesFieldLabel": "Valgte egenskaber",
        "LoadingMessage": "Henter resultater, vent venligst...",
        "EnableLocalizationLabel": "Aktivér lokalisering af taksonomiværdier for begrænsninger og resultat",
        "EnableLocalizationOnLabel": "Lokalisering aktiveret",
        "EnableLocalizationOffLabel": "Lokalisering deaktiveret",
        "NoResultMessage": "Ingen resultater at vise",
        "FilterPanelTitle": "Tilgængelige filtre",
        "FilterResultsButtonLabel": "Filtre",
        "SelectedFiltersLabel": "Valgte filtre",
        "SearchResultsLabel": "Søg resultater",
        "RemoveAllFiltersLabel": "Fjern alle filtre",
        "UsePaginationWebPartLabel": "Tilslut til en søgepaginerings-webdel",
        "ShowResultsCountLabel": "Vis antal svar",
        "ShowBlankLabel": "Vis blank hvis intet resultat",
        "ShowBlankEditInfoMessage": "Intet resultat returneret for denne forespørgsel. Denne webdel vil forblive blank i visningstilstand i overensstemmelse med parametrene.",
        "NoFilterConfiguredLabel": "Intet filter konfigureret",
        "SearchQueryPlaceHolderText": "Søgeforespørgsel i KQL-format",
        "EmptyFieldErrorMessage": "Dette felt må ikke være tomt",
        "PlaceHolderEditLabel": "Rediger",
        "PlaceHolderConfigureBtnLabel": "Konfigurér",
        "PlaceHolderIconText": "Søgeresultat webdel",
        "PlaceHolderDescription": "Dette komponent viser søgeresultater med sideinddeling",
        "ResultSourceIdLabel": "Resultatkilde-id/ Navn",
        "ResultSourceIdDescription": "Når navnet anvendes, benyt venligst dette format: Kildeniveau|Navn (fx: SPSite|Mine nyheder). Gyldige niveauer er: SPSiteSubscription, SPSite, SPWeb",
        "InvalidResultSourceIdMessage": "Indsæt enten et resultatkilde-id (guid) eller et navn med format: Niveau|Navn (fx: SPSite|Min resultatkilde)",
        "InvalidNumberIntervalMessage": "Mellem 1 og 500",
        "EnableQueryRulesLabel": "Aktivér forespørgselsregler",
        "IncludeOneDriveResultsLabel": "Inkluder personlige OneDrive-resultater",
        "StylingSettingsGroupName": "Stylingmuligheder",
        "SelectedPropertiesFieldDescription": "Specificerer egenskaberne for at hente fra søgeresultaterne.",
        "SearchQueryKeywordsFieldDescription": "Anvend predefinerede søgord i søgeforespørgsler for at hente et statistisk sæt af resultater.",
        "CountMessageLong": "<b>{0}</b> resultat for '<em>{1}</em>'",
        "CountMessageShort": "<b>{0}</b> resultat",
        "CancelButtonText": "Afbryd",
        "DialogButtonLabel": "Rediger skabelon",
        "DialogButtonText": "Rediger skabelon",
        "DialogTitle": "Rediger resultatskabelon",
        "SaveButtonText": "Gem",
        "SimpleListLayoutOption": "Enkel liste",
        "DetailsListLayoutOption": "Detaljeret liste",
        "TilesLayoutOption": "Felt",
        "CustomLayoutOption": "Brugerdefineret",
        "DebugLayoutOption": "Fejlfinde",
        "SliderLayoutOption": "Karrusel",
        "PeopleLayoutOption": "Personer",
        "ResultsLayoutLabel": "Resultatlayout",
        "TemplateUrlFieldLabel": "Anvend en ekstern URL-skabelon",
        "TemplateUrlPlaceholder": "https://myfile.html",
        "ErrorTemplateExtension": "Skabelonen skal være en gyldig .htm eller .html fil",
        "ErrorTemplateResolve": "Den specificerede skabelon kunne ikke løses. Fejldetaljer: '{0}'",
        "WebPartTitle": "Webdels-titel",
        "HandlebarsHelpersDescription": "Aktivér funktioner fra moment og handlebars. Se https://github.com/SharePoint/sp-dev-fx-webparts/blob/master/samples/react-search-refiners/README.md#available-tokens for mere information.",
        "PromotedResultsLabel": "Promoveret resultat(er)",
        "PanelCloseButtonAria": "Luk",
        "UseRefinersWebPartLabel": "Tilslut til en søgefiltreret webdel",
        "UseRefinersFromComponentLabel": "Anvend filtrerings-webdelen fra denne komponent",
        "UseSearchVerticalsLabel": "Tilslut til en søgevertikal webdel",
        "UsePaginationFromComponentLabel": "Anvend paginering fra denne komponent",
        "RefinementFilters": "Forfiningsfiltre",
        "customTemplateFieldsLabel": "Tilpasset skabelonfeltværdier",
        "customTemplateFieldsPanelHeader": "Tilpasset skabelonfeltværdier",
        "customTemplateFieldsConfigureButtonLabel": "Konfigurér",
        "customTemplateFieldTitleLabel": "Feltnavn",
        "customTemplateFieldPropertyLabel": "Søg egenskaber",
        "Sort": {
            "SortableFieldsPropertyPaneField": "Sorterbare egenskaber",
            "SortableFieldsDescription": "Specificerer sorterbare egenskaber som brugere kan anvende i brugergrænsefladen. Kun én egenskab ad gangen til sortering og vil for tilsidesætte den specificerede søgerækkefølge i WP, hvis den findes.",
            "SortPropertyPaneFieldLabel": "Sorteringsrækkefølge",
            "SortListDescription": "Specificer sorteringsrækkefølgen for søgeresultaterne. Dette anvendes kun, når der ikke er indstillet manuelle filtre (fx sorterbare felter)",
            "SortDirectionAscendingLabel": "Stigende",
            "SortDirectionDescendingLabel": "Faldende",
            "SortErrorMessage": "Ugyldig søgeegenskab (kontroller at egenskaben er sorterbar).",
            "SortPanelSortFieldLabel": "Sortér efter felt",
            "SortPanelSortFieldAria": "Sortér efter",
            "SortPanelSortFieldPlaceHolder": "Sortér efter",
            "SortPanelSortDirectionLabel": "Sortér retning",
            "SortableFieldManagedPropertyField": "Sortér håndteret egenskab",
            "SortableFieldDisplayValueField": "Feltnavn som skal vises",
            "EditSortableFieldsLabel": "Rediger sorterbare felter",
            "EditSortLabel": "Rediger sorgeringsrækkefølge",
            "EditSortLabelFieldName": "Feltnavn",
            "EditSortDirection": "Sortér retning",
            "SortInvalidSortableFieldMessage": "Denne egenskab er ikke sortbérbar"
        },
        "Synonyms": {
            "EditSynonymLabel": "Rediger synonymer",
            "SynonymListDescription": "Specificer alle synonymer der skal bruges i søgninger. Hvert term pr. søgning vil forbedres med alle tilknyttede synonymer, når forespørgslen sendes til serveren. Hvis et synonym indeholder mere end et ord, skal det markeres med citationstegn.",
            "SynonymPropertyPanelFieldLabel": "Konfigurér synonymer",
            "SynonymListTerm": "Term",
            "SynonymListSynonyms": "Synonymer",
            "SynonymIsTwoWays": "Begge veje?",
            "SynonymListSynonymsExemple": "Bærbar, \"Skrivebord med skærm\"",
            "SynonymListTermExemple": "Computer"
        },
        "TermNotFound": "(Term med ID '{0}' ej fundet)",
        "UseDefaultSearchQueryKeywordsFieldLabel": "Anvend en standard søgeforespørgsel",
        "DefaultSearchQueryKeywordsFieldLabel": "Standard søgeforespørgsel",
        "DefaultSearchQueryKeywordsFieldDescription": "Denne forespørgsel finder anvendelse, når værdien af datakilden stadig er tom.",
        "ResultTypes": {
            "ResultTypeslabel": "Resultattyper",
            "ResultTypesDescription": "Tilføj her den visningsskabelon der skal bruges til resultatartikler, der er overensstemmende med en eller flere betingelser. Betingelser evalueres i den konfigurerede rækkefølge og ektern skabelon har forrang over inline skabeloner. Sørg for at de håndterede egenskaber, du anvender, findes i de 'Valgte egenskaber' i denne webdel.",
            "InlineTemplateContentLabel": "Inline skabelon",
            "EditResultTypesLabel": "Rediger resultattyper",
            "ConditionPropertyLabel": "Håndterede egenskaber",
            "ConditionValueLabel": "Værdi",
            "CondtionOperatorValue": "Vilkår",
            "ExternalUrlLabel": "Ekstern skabelon-URL",
            "ExternalUrlPlaceholder": "https://mysite/Documents/external.html",
            "EqualOperator": "Er lig med",
            "NotEqualOperator": "Er ikke lig med",
            "ContainsOperator": "Indeholder",
            "StartsWithOperator": "Starter med",
            "NotNullOperator": "Er ikke nul",
            "GreaterOrEqualOperator": "Større end eller lig med",
            "GreaterThanOperator": "Større end",
            "LessOrEqualOperator": "Mindre end eller lig med",
            "LessThanOperator": "Mindre end"
        },
        "QueryCultureLabel": "Sprog for søgeanmodning",
        "QueryCultureUseUiLanguageLabel": "Anvend brugerfladesprog",
        "TemplateParameters": {
            "TemplateParametersGroupName": "Skabelonalternativer",
            "EnableItemPreview": "Aktivér forhåndsvisning af resultat",
            "ShowFileIcon": "Vis filikon",
            "ManageDetailsListColumnDescription": "Tilføj, opdater eller fjern kolonner for layoutet af den detaljerede liste. Du kan enten anvende den håndterede enhedsværdi direkte uden nogle transformationer, eller du kan anvende Handlebars-udtryk i værdifeltet. Alle felter supporterer HTML.",
            "ManageDetailsListColumnLabel": "Håndter kolonner",
            "ManageTilesFieldsLabel": "Håndtér kortfelter",
            "ManagePeopleFieldsLabel": "Håndtér personfelter",
            "ManagePeopleFieldsPanelDescriptionLabel": "Her kan du mappe hver feltværdi med det tilsvarende personfelt. Du kan enten anvende den håndterede enhed direkte uden nogen transformation, eller du kan anvende Handlebars-udtryk i værdifeltet.",
            "ManageTilesFieldsPanelDescriptionLabel": "Her kan du mappe hver feltværdi med det tilsvarende kortfelt. Du kan enten anvende den håndterede enhed direkte uden nogen transformation, eller du kan anvende Handlebars-udtryk i værdifeltet. Derudover kan du, når det indikeres, tilføre din egen HTML-kode i nogle felter.",
            "PlaceholderNameFieldLabel": "Navn",
            "PlaceholderValueFieldLabel": "Værdi",
            "ValueColumnLabel": "Kolonneværdi",
            "DisplayNameColumnLabel": "Kolonne visningsnavn",
            "UseHandlebarsExpressionLabel": "Anvend Handlebars-udtryk",
            "MinimumWidthColumnLabel": "Mindste bredde (px)",
            "MaximumWidthColumnLabel": "Største bredde (px)",
            "SortableColumnLabel": "Sorterbart",
            "ResizableColumnLabel": "Skalerbart",
            "MultilineColumnLabel": "Flere linjer",
            "LinkToItemColumnLabel": "Link til artikel",
            "SupportHTMLColumnLabel": "Tillad HTML",
            "CompactModeLabel": "Kompakt tilstand",
            "SliderAutoPlayDuration": "Avancering hvert (sekund)",
            "SliderAutoPlay": "Afspil automatisk",
            "SliderPauseAutoPlayOnHover": "Stop med at holde hen over",
            "SliderGroupCells": "Antal elementer som skal grupperes i billeder",
            "SliderShowPageDots": "Vis sideprikker",
            "SliderWrapAround": "Uendelig skærmrulning",
            "PersonaSizeOptionsLabel": "Billedestørrelse",
            "PersonaSizeExtraSmall": "Ekstra lille",
            "PersonaSizeSmall": "Lille",
            "PersonaSizeRegular": "Regulær",
            "PersonaSizeLarge": "Stor",
            "PersonaSizeExtraLarge": "Ekstra stor",
        },
        "ManagedPropertiesListPlaceHolder": "Vælg eller tilføj en håndteret egenskab",
        "QueryModifier": {
            "FieldLbl": "Modifikation af søgeforespørgsler",
            "ConfigureBtn": "Konfigurér",
            "PanelHeader": "Konfigurér modifikationer af søgeforespørgsler",
            "PanelDescription": "Du kan kun associere en forespørgselsmodifikation til en søgeresultatswebdel",
            "EnableColumnLbl": "Aktiveret",
            "DisplayNameColumnLbl": "Navn",
            "DescriptionColumnLbl": "Beskrivelse",
            "SelectedQueryModifierLbl": "Valgte forespørgselsmodifikation: '{0}'"
        },
        "Paging": {
            "PagingOptionsGroupName": "Instilinger for sideinddeling",
            "ItemsCountPerPageFieldName": "Antal enheder pr side",
            "PagingRangeFieldName": "Antal sider som skal vises",
            "ShowPagingFieldName": "Vis sideinddeling",
            "HidePageNumbersFieldName": "Skjul sidenumre",
            "HideNavigationFieldName": "Skjul navigationsknapper (foregående side, næste side)",
            "HideFirstLastPagesFieldName": "Skjul første/sidste navigationsknapper",
            "HideDisabledFieldName": "Skjul navigationsknapper (foregående, næste, første, sidste) hvis de er inaktive.",
        }
    }
});
