define([], function() {
    return {
        "SearchQuerySettingsGroupName": "Konfiguration der Suchabfrage",
        "SearchSettingsGroupName": "Einstellungen für die Suche",
        "SearchQueryKeywordsFieldLabel": "Schlüsselwörter für Suchabfragen",
        "QueryTemplateFieldLabel": "Abfrage-Vorlage",
        "SelectedPropertiesFieldLabel": "Ausgewählte Eigenschaften",
        "LoadingMessage": "Ergebnisse werden geladen, bitte warten Sie...",
        "EnableLocalizationLabel": "Ermöglichen Sie die Lokalisierung von Taxonomiewerten für Einschränkungen und Ergebnisse",
        "EnableLocalizationOnLabel": "Lokalisierung aktiviert",
        "EnableLocalizationOffLabel": "Lokalisierung deaktiviert",
        "NoResultMessage": "Keine anzuzeigenden Ergebnisse",
        "FilterPanelTitle": "Verfügbare Filter",
        "FilterResultsButtonLabel": "Filter",
        "SelectedFiltersLabel": "Ausgewählte Filter",
        "SearchResultsLabel": "Suchergebnisse",
        "RemoveAllFiltersLabel": "Alle Filter entfernen",
        "UsePaginationWebPartLabel": "Mit einem Seitennavigations Webpart verbinden",
        "ShowResultsCountLabel": "Ergebnisanzahl anzeigen",
        "ShowBlankLabel": "Leer anzeigen, wenn kein Ergebnis",
        "ShowBlankEditInfoMessage": "Für diese Abfrage wurde kein Ergebnis zurückgegeben. Dieser Webpart bleibt im Anzeigemodus gemäss den Parameter leer.",
        "NoFilterConfiguredLabel": "Kein Filter konfiguriert",
        "SearchQueryPlaceHolderText": "Suchabfrage im KQL-Format",
        "EmptyFieldErrorMessage": "Dieses Feld darf nicht leer sein.",
        "PlaceHolderEditLabel": "Bearbeiten",
        "PlaceHolderConfigureBtnLabel": "Konfigurieren",
        "PlaceHolderIconText": "Suchergebnisse Webpart",
        "PlaceHolderDescription": "Diese Komponente zeigt Suchergebnisse mit Paging an",
        "ResultSourceIdLabel": "ID Suchergebnisquelle",
		"ResultSourceIdDescription": "Wenn Sie den Namen verwenden, verwenden Sie das Format: Quellenebene|Name (d.h.: SPSite|Meine Nachrichten). Gültige Ebenen sind: SPSiteAbonnement, SPSite, SPWeb",
        "InvalidResultSourceIdMessage": "Ungültige ID",
        "InvalidNumberIntervalMessage": "Zwischen 1 und 500",
        "EnableQueryRulesLabel": "Abfrageregeln aktivieren",
        "IncludeOneDriveResultsLabel": "Persönliche OneDrive Ergebnisse einbeziehen",
        "StylingSettingsGroupName": "Styling Optionen",
        "SelectedPropertiesFieldDescription": "Gibt die Eigenschaften an, die aus den Suchergebnissen abgerufen werden sollen.",
        "SearchQueryKeywordsFieldDescription": "Verwenden Sie vordefinierte Suchabfrage Schlüsselwörter, um einen statischen Satz von Ergebnissen abzurufen.",
        "CountMessageLong": "<b>{0}</b> Ergebnisse für '<em>{1}</em>'",
        "CountMessageShort": "<b>{0}</b> Ergebnisse",
        "CancelButtonText": "Abbrechen",
        "DialogButtonLabel": "Vorlage bearbeiten",
        "DialogButtonText": "Vorlage bearbeiten",
        "DialogTitle": "Suchergebnisvorlage bearbeiten",
        "SaveButtonText": "Speichern",
        "SimpleListLayoutOption": "Einfache Liste",
        "DetailsListLayoutOption": "Detailliste",
        "TilesLayoutOption": "Tiles",
        "CustomLayoutOption": "Benutzerdefiniert",
        "DebugLayoutOption": "Debug",
        "SliderLayoutOption": "Carousel",
        "PeopleLayoutOption": "Personen",
        "ResultsLayoutLabel": "Layout Resultate",
        "TemplateUrlFieldLabel": "Externe Vorlagen-URL verwenden",
        "TemplateUrlPlaceholder": "https://myfile.html",
        "ErrorTemplateExtension": "Die Vorlage muss eine gültige .htm- oder .html-Datei sein",
        "ErrorTemplateResolve": "Die angegebene Vorlage konnte nicht aufgelöst werden. Fehlerdetails: '{0}'",
        "WebPartTitle": "Webpart Titel",
        "HandlebarsHelpersDescription": "Funktionen von moment und Handlebars aktivieren. Siehe https://github.com/SharePoint/sp-dev-fx-webparts/blob/master/samples/react-search-refiners/README.md#available-tokens für weitere Informationen.",
        "PromotedResultsLabel": "Höhergestufte Ergebnis(se)",
        "PanelCloseButtonAria": "schliessen",
        "UseRefinersWebPartLabel": "Verbindung zu einem Sucheinschränkungs Webpart herstellen",
        "UseRefinersFromComponentLabel": "Einschränkungen aus dieser Komponente verwenden",
        "UseSearchVerticalsLabel": "Connect to a search vertical Web Part",
        "UsePaginationFromComponentLabel": "Paging aus dieser Komponente verwenden",
        "RefinementFilters": "Einschränkungsfilter",
        "customTemplateFieldsLabel": "Benutzerdefinierte Werte für Vorlagenfelder",
        "customTemplateFieldsPanelHeader": "Benutzerdefinierte Werte für Vorlagenfelder",
        "customTemplateFieldsConfigureButtonLabel": "Konfigurieren",
        "customTemplateFieldTitleLabel": "Feldname",
        "customTemplateFieldPropertyLabel": "Eigenschaft suchen",
        "Sort": {
            "SortableFieldsPropertyPaneField": "Sortierbare Eigenschaften",
            "SortableFieldsDescription": "Gibt sortierbare Eigenschaften an, die Benutzer in der Benutzeroberfläche verwenden können. Es kann jeweils nur eine Eigenschaft zur Sortierung verwendet werden. Diese überschreibt die im WP angegebene Suchreihenfolge.",
            "SortPropertyPaneFieldLabel": "Sortierreihenfolge",
            "SortListDescription": "Geben Sie die Sortierreihenfolge für die Suchergebnisse an. Sie wird nur angewendet, wenn keine manuellen Filter gesetzt wurden (d.h. sortierbare Felder)",
            "SortDirectionAscendingLabel": "Aufsteigend",
            "SortDirectionDescendingLabel": "Absteigend",
            "SortErrorMessage": "Ungültige Sucheigenschaft (Prüfen Sie, ob die verwaltete Eigenschaft sortierbar ist).",
            "SortPanelSortFieldLabel": "Sortieren nach Feld",
            "SortPanelSortFieldAria": "Sortieren nach",
            "SortPanelSortFieldPlaceHolder": "Sortieren nach",
            "SortPanelSortDirectionLabel": "Sortierreihenfolge",
            "SortableFieldManagedPropertyField": "Verwaltete Eigenschaft sortieren",
            "SortableFieldDisplayValueField": "Anzuzeigender Feldname",
            "EditSortableFieldsLabel": "Sortierbare Felder bearbeiten",
            "EditSortLabel": "Sortierung bearbeiten",
            "EditSortLabelFieldName": "Feild namme",
            "EditSortDirection": "Sort Direction",
            "SortInvalidSortableFieldMessage": "Diese Eigenschaft ist nicht sortierbar"
        },
        "Synonyms": {
            "EditSynonymLabel": "Synonyme bearbeiten",
            "SynonymListDescription": "Geben Sie alle Synonyme an, die bei der Suche verwendet werden sollen. Jeder Suchbegriff wird mit allen zugehörigen Synonymen ergänzt, wenn die Abfrage an den Server gesendet wird. Wenn ein Synonym mehr als ein Wort enthält, muss es in doppelte Anführungszeichen gesetzt werden.",
            "SynonymPropertyPanelFieldLabel": "Konfigurieren von Synonymen",
            "SynonymListTerm": "Term",
            "SynonymListSynonyms": "Synonyme",
            "SynonymIsTwoWays": "Bidirektional?",
            "SynonymListSynonymsExemple": "Laptop, \"Desktop mit Monitor\"",
            "SynonymListTermExemple": "Computer"
        },
        "TermNotFound": "(Begriff mit ID '{0}' nicht gefunden)",
        "UseDefaultSearchQueryKeywordsFieldLabel": "Standard Suchabfrage verwenden",
        "DefaultSearchQueryKeywordsFieldLabel": "Standard Suchabfrage",
        "DefaultSearchQueryKeywordsFieldDescription": "Diese Abfrage wird verwendet, wenn der Wert der Datenquelle noch leer ist.",
        "ResultTypes": {
            "ResultTypeslabel": "Ergebnistypen",
            "ResultTypesDescription": "Fügen Sie hier die Anzeigevorlagen hinzu, die für Ergebniselemente gemäss einer oder mehrerer Bedingungen zu verwenden sind. Bedingungen werden in der konfigurierten Reihenfolge ausgewertet und externe Vorlagen haben Vorrang vor Inline-Vorlagen. Stellen Sie sicher, dass die verwendeten Verwalteten Eigenschaften in den 'Ausgewählten Eigenschaften' dieses Webparts vorhanden sind.",
            "InlineTemplateContentLabel": "Inline-Vorlage",
            "EditResultTypesLabel": "Ergebnistypen bearbeiten",
            "ConditionPropertyLabel": "Verwaltete Eigenschaft",
            "ConditionValueLabel": "Bedingung",
            "CondtionOperatorValue": "Operator",
            "ExternalUrlLabel": "Externe Vorlagen-URL",
            "ExternalUrlPlaceholder": "https://mysite/Documents/external.html",
            "EqualOperator": "Entspricht",
            "NotEqualOperator": "Nicht gleich",
            "ContainsOperator": "Enthält",
            "StartsWithOperator": "Beginnt mit",
            "NotNullOperator": "Ist ungleich null",
            "GreaterOrEqualOperator": "Grösser als oder gleich",
            "GreaterThanOperator": "Grösser als",
            "LessOrEqualOperator": "Kleiner als oder gleich",
            "LessThanOperator": "Kleiner als"
        },
        "QueryCultureLabel": "Sprache der Suchabfrage",
        "QueryCultureUseUiLanguageLabel": "Schnittstellensprache verwenden",
        "TemplateParameters": {
            "TemplateParametersGroupName": "Vorlagen Optionen",
            "EnableItemPreview": "Ergebnisvorschau aktivieren",
            "ShowFileIcon": "Dateisymbol anzeigen",
            "ManageDetailsListColumnDescription": "Hinzufügen, Aktualisieren oder Entfernen von Spalten für das Layout der Detailliste. Sie können entweder den verwalteten Eigenschaftswert direkt ohne jegliche Transformation verwenden oder einen Handlebars-Ausdruck im Wertefeld verwenden. HTML wird ebenfalls für alle Felder unterstützt.",
            "ManageDetailsListColumnLabel": "Spalten verwalten",
            "ManageTilesFieldsLabel": "Tiles verwalten",
            "ManagePeopleFieldsLabel": "Persona-Felder verwalten",
            "ManagePeopleFieldsPanelDescriptionLabel": "Hier können Sie die einzelnen Feldwerte mit den entsprechenden Persona-Platzhaltern abbilden. Sie können entweder den verwalteten Eigenschaftswert direkt ohne jegliche Transformation verwenden oder einen Handlebars-Ausdruck im Wertefeld verwenden.",
            "ManageTilesFieldsPanelDescriptionLabel": "Hier können Sie die einzelnen Feldwerte mit den entsprechenden Tile-Platzhaltern abbilden. Sie können entweder den verwalteten Eigenschaftswert direkt ohne jegliche Transformation verwenden oder einen Handlebars-Ausdruck im Wertefeld verwenden. Ausserdem können Sie, wenn angegeben, in einigen Feldern auch Ihren eigenen HTML-Code einfügen.",
            "PlaceholderNameFieldLabel": "Name",
            "PlaceholderValueFieldLabel": "Wert",
            "ValueColumnLabel": "Spaltenwert",
            "DisplayNameColumnLabel": "Name der Spaltenanzeige",
            "UseHandlebarsExpressionLabel": "Handlebars Ausdruck verwenden",
            "MinimumWidthColumnLabel": "Minimale Breite (px)",
            "MaximumWidthColumnLabel": "Maximale Breite (px)",
            "SortableColumnLabel": "Sortierbar",
            "ResizableColumnLabel": "Breite anpassbar",
            "MultilineColumnLabel": "Mehrzeilig",
            "LinkToItemColumnLabel": "Link zum Artikel",
            "SupportHTMLColumnLabel": "HTML zulassen",
            "CompactModeLabel": "Kompakt-Modus",
            "SliderAutoPlayDuration": "Wechsle Element alle (Sekunden)",
            "SliderAutoPlay": "Automatische Wiedergabe",
            "SliderPauseAutoPlayOnHover": "Pause bei Hover",
            "SliderGroupCells": "Anzahl Elemente pro Slide",
            "SliderShowPageDots": "Sliderpunkte anzeigen",
            "SliderWrapAround": "Infinite Scrolling",
            "PersonaSizeOptionsLabel": "Bildgrösse",
            "PersonaSizeExtraSmall": "Extra klein",
            "PersonaSizeSmall": "Klein",
            "PersonaSizeRegular": "Regulär",
            "PersonaSizeLarge": "Gross",
            "PersonaSizeExtraLarge": "Extra gross",
        },
        "ManagedPropertiesListPlaceHolder": "Auswählen oder Hinzufügen einer verwalteten Eigenschaft",
        "QueryModifier": {
            "FieldLbl": "Suchabfrage Modifikatoren",
            "ConfigureBtn": "Konfigurieren",
            "PanelHeader": "Konfigurieren von Suchabfrage-Modifikatoren",
            "PanelDescription": "Sie können einem Suchresultat Webpart nur einen Abfragemodifikator zuordnen",
            "EnableColumnLbl": "Aktiviert",
            "DisplayNameColumnLbl": "Name",
            "DescriptionColumnLbl": "Beschreibung",
            "SelectedQueryModifierLbl": "Ausgewählter Abfragemodifikator: '{0}'"
        },
        "Paging": {
            "PagingOptionsGroupName": "Paging-Einstellungen",
            "ItemsCountPerPageFieldName": "Anzahl der Artikel pro Seite",
            "PagingRangeFieldName": "Anzahl der anzuzeigenden Seiten im Bereich",
            "ShowPagingFieldName": "Paging anzeigen",
            "HidePageNumbersFieldName": "Seitenzahlen ausblenden",
            "HideNavigationFieldName": "Navigationsschaltflächen ausblenden (vorherige Seite, nächste Seite)",
            "HideFirstLastPagesFieldName": "Erste/letzte Navigationschaltfläche ausblenden",
            "HideDisabledFieldName": "Navigationsschaltflächen (zurück, nächste, erste, letzte) ausblenden, wenn sie deaktiviert sind.",
        }
    }
});