define([], function() {
    return {
        "SearchQuerySettingsGroupName": "Inställningar för sökfrågor",
        "SearchSettingsGroupName": "Inställningar för sök",
        "SearchQueryKeywordsFieldLabel": "Sökord för sökfrågor",
        "QueryTemplateFieldLabel": "Frågemall",
        "SelectedPropertiesFieldLabel": "Valda värden",
        "LoadingMessage": "Resultaten laddas, vänligen vänta...",
        "EnableLocalizationLabel": "Aktivera lokalisering för taxonomi värden för begränsningar och resultat",
        "EnableLocalizationOnLabel": "Lokalisering aktiverad",
        "EnableLocalizationOffLabel": "Lokalisering avaktiverad",
        "NoResultMessage": "Inga resultat att visa",
        "FilterPanelTitle": "Tillgängliga filter",
        "FilterResultsButtonLabel": "Filter",
        "SelectedFiltersLabel": "Valda filter",
        "SearchResultsLabel": "Sökresultat",
        "RemoveAllFiltersLabel": "Ta bort alla filter",
        "UsePaginationWebPartLabel": "Anslut till sök sidor webbdel",
        "ShowResultsCountLabel": "Visa antal svar",
        "ShowBlankLabel": "Visa tomt om inget resultat",
        "ShowBlankEditInfoMessage": "Inget resultat returnerades för den här frågan. Denna webbdel kommer att förbli tom i visningsläge enligt inställningar",
        "NoFilterConfiguredLabel": "Inget filter konfigurerat",
        "SearchQueryPlaceHolderText": "Sökfråga i KQL-format",
        "EmptyFieldErrorMessage": "Detta fält kan inte vara tomt",
        "PlaceHolderEditLabel": "Redigera",
        "PlaceHolderConfigureBtnLabel": "Konfigurera",
        "PlaceHolderIconText": "Sökresultat webbdel",
        "PlaceHolderDescription": "Den här komponenten visar sökresultat med sidindelning",
        "ResultSourceIdLabel": "Resultatkälla-id / namn",
        "ResultSourceIdDescription": "När du använder namnet använd formatet: Källnivå|Namn (dvs: SPSite|Mina nyheter). Giltiga nivåer är: SPSiteSubscription, SPSite, SPWeb",
        "InvalidResultSourceIdMessage": "Ange antingen en resultatkällas id (guid) eller ett namn med formatet: Nivå|Namn (dvs: SPSite|Min resultatkälla)",								
        "InvalidNumberIntervalMessage": "Mellan 1 och 500",
        "EnableQueryRulesLabel": "Aktivera frågaregler",
        "IncludeOneDriveResultsLabel": "Inkludera personliga OneDrive-resultat",
        "StylingSettingsGroupName": "Stylingalternativ",
        "SelectedPropertiesFieldDescription": "Anger egenskaperna som ska hämtas från sökresultaten.",
        "SearchQueryKeywordsFieldDescription": "Använd fördefinierade sökfrågeord för att hämta en statisk uppsättning av resultat.",
        "CountMessageLong": "<b>{0}</b> resultat för '<em>{1}</em>'",
        "CountMessageShort": "<b>{0}</b> resultat",
        "CancelButtonText": "Avbryt",
        "DialogButtonLabel": "Redigera mall",
        "DialogButtonText": "Redigera mall",
        "DialogTitle": "Redigera resultatmall",
        "SaveButtonText": "Spara",
        "SimpleListLayoutOption": "Enkel lista",
        "DetailsListLayoutOption": "Detaljerad lista",
        "TilesLayoutOption": "Kort",
        "CustomLayoutOption": "Anpassad",
        "DebugLayoutOption": "Debug",
        "SliderLayoutOption": "Karusell",
        "PeopleLayoutOption": "Personer",
        "ResultsLayoutLabel": "Resultatlayout",
        "TemplateUrlFieldLabel": "Använd en extern mall-URL",
        "TemplateUrlPlaceholder": "https://myfile.html",
        "ErrorTemplateExtension": "Mallen måste vara en giltig .htm- eller .html-fil",
        "ErrorTemplateResolve": "Det gick inte att tolka den angivna mallen. Felinformation: '{0}'",
        "WebPartTitle": "Webbdels titel",
        "HandlebarsHelpersDescription": "Aktivera funktioner från moment and handlebars. Se https://github.com/SharePoint/sp-dev-fx-webparts/blob/master/samples/react-search-refiners/README.md#available-tokens för mer information.",
        "PromotedResultsLabel": "Rekomenderade resultat",
        "PanelCloseButtonAria": "Stäng",
        "UseRefinersWebPartLabel": "Anslut till filter webbdel",
        "UseRefinersFromComponentLabel": "Använd filtrerings webbdelen från denna komponent",
        "UseSearchVerticalsLabel": "Anslut till vertikal webbdel",
        "UsePaginationFromComponentLabel": "Använd sidindelning från denna komponent",
        "RefinementFilters": "Förfiningsfilter",
        "customTemplateFieldsLabel": "Anpassade mallfältvärden",
        "customTemplateFieldsPanelHeader": "Anpassade mallfältvärden",
        "customTemplateFieldsConfigureButtonLabel": "Konfigurera",
        "customTemplateFieldTitleLabel": "Fält namn",
        "customTemplateFieldPropertyLabel": "Sök egenskaper",
        "Sort": {
            "SortableFieldsPropertyPaneField": "Sorterbara egenskaper",
            "SortableFieldsDescription": "Anger sorterbara egenskaper som användare kan använda i användargränssnittet. Endast en egenskap kan användas i taget för sortering och kommer att åsidosätta den sökordning som anges i WP om den finns.",
            "SortPropertyPaneFieldLabel": "Sorteringsordning",
            "SortListDescription": "Ange sorteringsordningen för sökresultaten. Detta kommer endast att tillämpas när inga manuella filter har ställts in (t.ex. sorterbara fält)",
            "SortDirectionAscendingLabel": "Stigande",
            "SortDirectionDescendingLabel": "Fallande",
            "SortErrorMessage": "Ogiltig sökegenskap (Kontrollera om den hanterade egenskapen är sorterbar).",
            "SortPanelSortFieldLabel": "Sortera på fält",
            "SortPanelSortFieldAria": "Sortera efter",
            "SortPanelSortFieldPlaceHolder": "Sortera efter",
            "SortPanelSortDirectionLabel": "Sorteringsriktning",
            "SortableFieldManagedPropertyField": "Sortera hanterade egenskaper",
            "SortableFieldDisplayValueField": "Fältnamn som ska visas",
            "EditSortableFieldsLabel": "Redigera sorterbara fält",
            "EditSortLabel": "Redigera sorteringsordning",
            "EditSortLabelFieldName": "Fält nammn",
            "EditSortDirection": "Sorteringsriktning",
            "SortPanelSortDirectionLabel": "Sorteringsriktning",
            "SortInvalidSortableFieldMessage": "Den här egenskapen är inte sorterbar"
        },
        "Synonyms": {
            "EditSynonymLabel": "Redigera synonymer",
            "SynonymListDescription": "Ange alla synonymer som kommer att användas när du söker. Varje Term sökning kommer att förbättras med alla tillhörande synonymer när frågan skickas till servern. Om en synonym innehåller mer än ett ord, måste det förpackas med citationstecken.",
            "SynonymPropertyPanelFieldLabel": "Konfigurera synonymer",
            "SynonymListTerm": "Term",
            "SynonymListSynonyms": "Synonymer",
            "SynonymIsTwoWays": "Båda vägarna?",
            "SynonymListSynonymsExemple": "Bärbar, \"Skrivbord med skärm\"",
            "SynonymListTermExemple": "Dator"
        },
        "TermNotFound": "(Term med ID '{0}' hittades inte)",
        "UseDefaultSearchQueryKeywordsFieldLabel": "Använd en standardsökfråga",
        "DefaultSearchQueryKeywordsFieldLabel": "Standardsökfråga",
        "DefaultSearchQueryKeywordsFieldDescription": "Denna fråga kommer att användas när värdet på datakällan fortfarande är tomt.",
        "ResultTypes": {
            "ResultTypeslabel": "Resultattyper",
            "ResultTypesDescription": "Lägg till visningsmallarna som ska användas för resultatartiklar enligt en eller flera förhållanden. Förhållandena utvärderas i den konfigurerade ordningen och externa mallar har företräde framför inline mallar. Se till att de hanterade egenskaperna du använder finns i de 'Valda egenskaperna' i denna webbdel.",
            "InlineTemplateContentLabel": "Inline mall",
            "EditResultTypesLabel": "Redigera resultattyper",
            "ConditionPropertyLabel": "Hanterade egenskaper",
            "ConditionValueLabel": "Värde",
            "CondtionOperatorValue": "Vilkor",
            "ExternalUrlLabel": "Extern mall-URL",
            "ExternalUrlPlaceholder": "https://mysite/Documents/external.html",
            "EqualOperator": "Lika med",
            "NotEqualOperator": "Inte lika med",
            "ContainsOperator": "Innehåller",
            "StartsWithOperator": "Börjar med",
            "NotNullOperator": "Är inte noll",
            "GreaterOrEqualOperator": "Större än eller lika med",
            "GreaterThanOperator": "Större än",
            "LessOrEqualOperator": "Mindre än eller lika med",
            "LessThanOperator": "Mindre än"
        },
        "QueryCultureLabel": "Språk för sökförfrågan",
        "QueryCultureUseUiLanguageLabel": "Använd gränssnittsspråk",
        "TemplateParameters": {
            "TemplateParametersGroupName": "Mallalternativ",
            "EnableItemPreview": "Aktivera förhandsgranskning",
            "ShowFileIcon": "Visa filikonen",
            "ManageDetailsListColumnDescription": "Lägg till, uppdatera eller ta bort kolumner för detaljerad lista. Du kan använda antingen det hanterade egenskapsvärdet direkt utan någon omvandling eller använda ett Handlebar uttryck i värdefältet. Alla fält stöder HTML.",
            "ManageDetailsListColumnLabel": "Hantera kolumner",
            "ManageTilesFieldsLabel": "Hantera kort-fält",
            "ManagePeopleFieldsLabel": "Hantera person-fält",
            "ManagePeopleFieldsPanelDescriptionLabel": "Här kan du matcha varje fältvärde med ett motsvarande person-fält. Du kan använda antingen det hanterade egenskapsvärdet direkt utan någon omvandling eller använda ett Handlebar uttryck i värdefältet.",
            "ManageTilesFieldsPanelDescriptionLabel": "Här kan du matcha varje fältvärde med ett motsvarande kort-fält. Du kan använda antingen det hanterade egenskapsvärdet direkt utan någon omvandling eller använda ett Handlebar uttryck i värdefältet.",
            "PlaceholderNameFieldLabel": "Namn",
            "PlaceholderValueFieldLabel": "Värde",
            "ValueColumnLabel": "Kolumnvärde",
            "DisplayNameColumnLabel": "Kolumnens visningsnamn",
            "UseHandlebarsExpressionLabel": "Använd Handlebars uttryck",
            "MinimumWidthColumnLabel": "Minsta bredd (px)",
            "MaximumWidthColumnLabel": "Största bredd (px)",
            "SortableColumnLabel": "Sorterbart",
            "ResizableColumnLabel": "Skalbar",
            "MultilineColumnLabel": "Flera   rader",
            "LinkToItemColumnLabel": "Länk till",
            "SupportHTMLColumnLabel": "Tillåt HTML",
            "CompactModeLabel": "Kompakt läge",
            "SliderAutoPlayDuration": "Avancering var (sekund)",
            "SliderAutoPlay": "Spela automatiskt",
            "SliderPauseAutoPlayOnHover": "Stanna vid hovrande över",
            "SliderGroupCells": "Antal element som ska grupperas i bilder",
            "SliderShowPageDots": "Visa sidprickar",
            "SliderWrapAround": "Oändlig rullning",
            "PersonaSizeOptionsLabel": "Bildstorlek",
            "PersonaSizeExtraSmall": "Extra liten",
            "PersonaSizeSmall": "Liten",
            "PersonaSizeRegular": "Fyrkantig",
            "PersonaSizeLarge": "Stor",
            "PersonaSizeExtraLarge": "Extra stor",
        },
        "ManagedPropertiesListPlaceHolder": "Välj eller lägg till en hanterad egenskap",
        "QueryModifier": {
            "FieldLbl": "Modifiering av sökfråga",
            "ConfigureBtn": "Konfigurera",
            "PanelHeader": "Konfigurera sökfrågor",
            "PanelDescription": "Du kan bara koppla en frågemodifierare till ett sökresultat-webbdel",
            "EnableColumnLbl": "Aktiverad",
            "DisplayNameColumnLbl": "Namn",
            "DescriptionColumnLbl": "Beskrivning",
            "SelectedQueryModifierLbl": "Vald sökmodifierare: '{0}'"
        },
        "Paging": {
            "PagingOptionsGroupName": "Inställningar för sidindelning",
            "ItemsCountPerPageFieldName": "Antal svar per sida",
            "PagingRangeFieldName": "Antal sidor som ska visas",
            "ShowPagingFieldName": "Visa sidindelning",
            "HidePageNumbersFieldName": "Dölj sidnummer",
            "HideNavigationFieldName": "Dölj navigeringsval (föregående sida, nästa sida)",
            "HideFirstLastPagesFieldName": "Dölj första och sista navigeringsval",
            "HideDisabledFieldName": "Dölj navigeringsval (föregående, nästa, första, sista) om de är inaktiverade.",
        }
    }
});
