// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'errorMessage': string;
  'loadingIndicator': string;
  'parentStackingCtx': string;
  'searchBox': string;
  'searchBoxWrapper': string;
  'searchButton': string;
  'searchTextField': string;
  'suggestionAction': string;
  'suggestionContainer': string;
  'suggestionContent': string;
  'suggestionDescription': string;
  'suggestionDisplayText': string;
  'suggestionGroupName': string;
  'suggestionIcon': string;
  'suggestionItem': string;
  'suggestionPanel': string;
}
export const cssExports: CssExports;
export default cssExports;
